# Generated by Django 4.2.9 on 2026-04-01 17:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("waitlist", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="waitlistentry",
            name="joined_at",
        ),
        migrations.RemoveField(
            model_name="waitlistentry",
            name="pledged_price",
        ),
        migrations.AddField(
            model_name="waitlistentry",
            name="city",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="waitlistentry",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="waitlistentry",
            name="is_pledge",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="waitlistentry",
            name="name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="waitlistentry",
            name="phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="waitlistentry",
            name="requirements",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="waitlistentry",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="waitlist_entries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
